package entity;

import com.google.gson.annotations.SerializedName;

public class PlaylistResult {
    @SerializedName("items")
    public Item[] items;


    public Item[] getItemsArray() {
        return items;
    }

}


/*
{
        "collaborative": false,
        "description": "",
        "external_urls": {
        "spotify": "https://open.spotify.com/playlist/4bPkJ6MbqZFpj4y1jLhAPi"
        },
        "followers": {
        "href": null,
        "total": 0
        },
        "href": "https://api.spotify.com/v1/playlists/4bPkJ6MbqZFpj4y1jLhAPi",
        "id": "4bPkJ6MbqZFpj4y1jLhAPi",
        "images": [
        {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b2732160c02bc56f192df0f4986b",
        "width": 640
        }
        ],
        "name": "atest",
        "owner": {
        "display_name": "Amal Alexander Tharyan",
        "external_urls": {
        "spotify": "https://open.spotify.com/user/22w3l23dfnpu5vi2th3gvdbvi"
        },
        "href": "https://api.spotify.com/v1/users/22w3l23dfnpu5vi2th3gvdbvi",
        "id": "22w3l23dfnpu5vi2th3gvdbvi",
        "type": "user",
        "uri": "spotify:user:22w3l23dfnpu5vi2th3gvdbvi"
        },
        "primary_color": null,
        "public": true,
        "snapshot_id": "NCxlYTM0MjdjNzVmNzQ2OWYxNzBkNjllZTQxNTlmYjBhN2Q0NDg0ZmI4",
        "tracks": {
        "href": "https://api.spotify.com/v1/playlists/4bPkJ6MbqZFpj4y1jLhAPi/tracks?offset=0&limit=100",
        "items": [
        {
        "added_at": "2022-12-06T20:54:08Z",
        "added_by": {
        "external_urls": {
        "spotify": "https://open.spotify.com/user/22w3l23dfnpu5vi2th3gvdbvi"
        },
        "href": "https://api.spotify.com/v1/users/22w3l23dfnpu5vi2th3gvdbvi",
        "id": "22w3l23dfnpu5vi2th3gvdbvi",
        "type": "user",
        "uri": "spotify:user:22w3l23dfnpu5vi2th3gvdbvi"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
        "album": {
        "album_type": "album",
        "artists": [
        {
        "external_urls": {
        "spotify": "https://open.spotify.com/artist/5rSXSAkZ67PYJSvpUpkOr7"
        },
        "href": "https://api.spotify.com/v1/artists/5rSXSAkZ67PYJSvpUpkOr7",
        "id": "5rSXSAkZ67PYJSvpUpkOr7",
        "name": "Backstreet Boys",
        "type": "artist",
        "uri": "spotify:artist:5rSXSAkZ67PYJSvpUpkOr7"
        }
        ],
        "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
        ],
        "external_urls": {
        "spotify": "https://open.spotify.com/album/5ySxm9hxBNss01WCL7GLyQ"
        },
        "href": "https://api.spotify.com/v1/albums/5ySxm9hxBNss01WCL7GLyQ",
        "id": "5ySxm9hxBNss01WCL7GLyQ",
        "images": [
        {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b2732160c02bc56f192df0f4986b",
        "width": 640
        },
        {
        "height": 300,
        "url": "https://i.scdn.co/image/ab67616d00001e022160c02bc56f192df0f4986b",
        "width": 300
        },
        {
        "height": 64,
        "url": "https://i.scdn.co/image/ab67616d000048512160c02bc56f192df0f4986b",
        "width": 64
        }
        ],
        "name": "Millennium",
        "release_date": "1999-05-18",
        "release_date_precision": "day",
        "total_tracks": 12,
        "type": "album",
        "uri": "spotify:album:5ySxm9hxBNss01WCL7GLyQ"
        },
        "artists": [
        {
        "external_urls": {
        "spotify": "https://open.spotify.com/artist/5rSXSAkZ67PYJSvpUpkOr7"
        },
        "href": "https://api.spotify.com/v1/artists/5rSXSAkZ67PYJSvpUpkOr7",
        "id": "5rSXSAkZ67PYJSvpUpkOr7",
        "name": "Backstreet Boys",
        "type": "artist",
        "uri": "spotify:artist:5rSXSAkZ67PYJSvpUpkOr7"
        }
        ],
        "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 213306,
        "episode": false,
        "explicit": false,
        "external_ids": {
        "isrc": "USJI19910614"
        },
        "external_urls": {
        "spotify": "https://open.spotify.com/track/47BBI51FKFwOMlIiX6m8ya"
        },
        "href": "https://api.spotify.com/v1/tracks/47BBI51FKFwOMlIiX6m8ya",
        "id": "47BBI51FKFwOMlIiX6m8ya",
        "is_local": false,
        "name": "I Want It That Way",
        "popularity": 81,
        "preview_url": "https://p.scdn.co/mp3-preview/3d0e33c987e5eec29c69691f7aa56fb0ee96bd92?cid=e2ea72863e3a4ec196da146a74a79aac",
        "track": true,
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:47BBI51FKFwOMlIiX6m8ya"
        },
        "video_thumbnail": {
        "url": null
        }
        },
        {
        "added_at": "2022-12-06T20:54:02Z",
        "added_by": {
        "external_urls": {
        "spotify": "https://open.spotify.com/user/22w3l23dfnpu5vi2th3gvdbvi"
        },
        "href": "https://api.spotify.com/v1/users/22w3l23dfnpu5vi2th3gvdbvi",
        "id": "22w3l23dfnpu5vi2th3gvdbvi",
        "type": "user",
        "uri": "spotify:user:22w3l23dfnpu5vi2th3gvdbvi"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
        "album": {
        "album_type": "album",
        "artists": [
        {
        "external_urls": {
        "spotify": "https://open.spotify.com/artist/7gOdHgIoIKoe4i9Tta6qdD"
        },
        "href": "https://api.spotify.com/v1/artists/7gOdHgIoIKoe4i9Tta6qdD",
        "id": "7gOdHgIoIKoe4i9Tta6qdD",
        "name": "Jonas Brothers",
        "type": "artist",
        "uri": "spotify:artist:7gOdHgIoIKoe4i9Tta6qdD"
        }
        ],
        "available_markets": [
        "US"
        ],
        "external_urls": {
        "spotify": "https://open.spotify.com/album/3tnBL4yVKSTaUtjeypEwCe"
        },
        "href": "https://api.spotify.com/v1/albums/3tnBL4yVKSTaUtjeypEwCe",
        "id": "3tnBL4yVKSTaUtjeypEwCe",
        "images": [
        {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b27378bff419e5eef1258f07aaa7",
        "width": 640
        },
        {
        "height": 300,
        "url": "https://i.scdn.co/image/ab67616d00001e0278bff419e5eef1258f07aaa7",
        "width": 300
        },
        {
        "height": 64,
        "url": "https://i.scdn.co/image/ab67616d0000485178bff419e5eef1258f07aaa7",
        "width": 64
        }
        ],
        "name": "It's About Time",
        "release_date": "2006-08-08",
        "release_date_precision": "day",
        "total_tracks": 11,
        "type": "album",
        "uri": "spotify:album:3tnBL4yVKSTaUtjeypEwCe"
        },
        "artists": [
        {
        "external_urls": {
        "spotify": "https://open.spotify.com/artist/7gOdHgIoIKoe4i9Tta6qdD"
        },
        "href": "https://api.spotify.com/v1/artists/7gOdHgIoIKoe4i9Tta6qdD",
        "id": "7gOdHgIoIKoe4i9Tta6qdD",
        "name": "Jonas Brothers",
        "type": "artist",
        "uri": "spotify:artist:7gOdHgIoIKoe4i9Tta6qdD"
        }
        ],
        "available_markets": [
        "US"
        ],
        "disc_number": 1,
        "duration_ms": 201813,
        "episode": false,
        "explicit": false,
        "external_ids": {
        "isrc": "USSM10602493"
        },
        "external_urls": {
        "spotify": "https://open.spotify.com/track/7BbyWKteSctTKe696qf7fw"
        },
        "href": "https://api.spotify.com/v1/tracks/7BbyWKteSctTKe696qf7fw",
        "id": "7BbyWKteSctTKe696qf7fw",
        "is_local": false,
        "name": "Year 3000",
        "popularity": 48,
        "preview_url": "https://p.scdn.co/mp3-preview/70dc01d619c8236befad36ea115e427aeb29e1b7?cid=e2ea72863e3a4ec196da146a74a79aac",
        "track": true,
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:7BbyWKteSctTKe696qf7fw"
        },
        "video_thumbnail": {
        "url": null
        }
        },
        {
        "added_at": "2022-12-06T20:53:44Z",
        "added_by": {
        "external_urls": {
        "spotify": "https://open.spotify.com/user/22w3l23dfnpu5vi2th3gvdbvi"
        },
        "href": "https://api.spotify.com/v1/users/22w3l23dfnpu5vi2th3gvdbvi",
        "id": "22w3l23dfnpu5vi2th3gvdbvi",
        "type": "user",
        "uri": "spotify:user:22w3l23dfnpu5vi2th3gvdbvi"
        },
        "is_local": false,
        "primary_color": null,
        "track": {
        "album": {
        "album_type": "album",
        "artists": [
        {
        "external_urls": {
        "spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"
        },
        "href": "https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
        "id": "06HL4z0CvFAxyc27GXpf02",
        "name": "Taylor Swift",
        "type": "artist",
        "uri": "spotify:artist:06HL4z0CvFAxyc27GXpf02"
        }
        ],
        "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
        ],
        "external_urls": {
        "spotify": "https://open.spotify.com/album/3lS1y25WAhcqJDATJK70Mq"
        },
        "href": "https://api.spotify.com/v1/albums/3lS1y25WAhcqJDATJK70Mq",
        "id": "3lS1y25WAhcqJDATJK70Mq",
        "images": [
        {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b273e0b60c608586d88252b8fbc0",
        "width": 640
        },
        {
        "height": 300,
        "url": "https://i.scdn.co/image/ab67616d00001e02e0b60c608586d88252b8fbc0",
        "width": 300
        },
        {
        "height": 64,
        "url": "https://i.scdn.co/image/ab67616d00004851e0b60c608586d88252b8fbc0",
        "width": 64
        }
        ],
        "name": "Midnights (3am Edition)",
        "release_date": "2022-10-22",
        "release_date_precision": "day",
        "total_tracks": 20,
        "type": "album",
        "uri": "spotify:album:3lS1y25WAhcqJDATJK70Mq"
        },
        "artists": [
        {
        "external_urls": {
        "spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"
        },
        "href": "https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
        "id": "06HL4z0CvFAxyc27GXpf02",
        "name": "Taylor Swift",
        "type": "artist",
        "uri": "spotify:artist:06HL4z0CvFAxyc27GXpf02"
        }
        ],
        "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 174782,
        "episode": false,
        "explicit": false,
        "external_ids": {
        "isrc": "USUG12205712"
        },
        "external_urls": {
        "spotify": "https://open.spotify.com/track/6Nl7KyvjkFncGsjB49SxLl"
        },
        "href": "https://api.spotify.com/v1/tracks/6Nl7KyvjkFncGsjB49SxLl",
        "id": "6Nl7KyvjkFncGsjB49SxLl",
        "is_local": false,
        "name": "Midnight Rain",
        "popularity": 86,
        "preview_url": "https://p.scdn.co/mp3-preview/df1caeeff164bcf376f418ce9c5aa5c71645cc79?cid=e2ea72863e3a4ec196da146a74a79aac",
        "track": true,
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:6Nl7KyvjkFncGsjB49SxLl"
        },
        "video_thumbnail": {
        "url": null
        }
        }
        ],
        "limit": 100,
        "next": null,
        "offset": 0,
        "previous": null,
        "total": 3
        },
        "type": "playlist",
        "uri": "spotify:playlist:4bPkJ6MbqZFpj4y1jLhAPi"
        }*/